// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ComputeService.proto

// Protobuf Java Version: 3.25.1
package src;

public final class ComputeServiceOuterClass {
  private ComputeServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ComputeRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ComputeRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string inputFile = 1;</code>
     * @return Whether the inputFile field is set.
     */
    boolean hasInputFile();
    /**
     * <code>optional string inputFile = 1;</code>
     * @return The inputFile.
     */
    java.lang.String getInputFile();
    /**
     * <code>optional string inputFile = 1;</code>
     * @return The bytes for inputFile.
     */
    com.google.protobuf.ByteString
        getInputFileBytes();

    /**
     * <code>optional string outputFile = 2;</code>
     * @return Whether the outputFile field is set.
     */
    boolean hasOutputFile();
    /**
     * <code>optional string outputFile = 2;</code>
     * @return The outputFile.
     */
    java.lang.String getOutputFile();
    /**
     * <code>optional string outputFile = 2;</code>
     * @return The bytes for outputFile.
     */
    com.google.protobuf.ByteString
        getOutputFileBytes();

    /**
     * <code>optional string delim = 3;</code>
     * @return Whether the delim field is set.
     */
    boolean hasDelim();
    /**
     * <code>optional string delim = 3;</code>
     * @return The delim.
     */
    java.lang.String getDelim();
    /**
     * <code>optional string delim = 3;</code>
     * @return The bytes for delim.
     */
    com.google.protobuf.ByteString
        getDelimBytes();
  }
  /**
   * Protobuf type {@code ComputeRequest}
   */
  public static final class ComputeRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ComputeRequest)
      ComputeRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ComputeRequest.newBuilder() to construct.
    private ComputeRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ComputeRequest() {
      inputFile_ = "";
      outputFile_ = "";
      delim_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ComputeRequest();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ComputeServiceOuterClass.internal_static_ComputeRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ComputeServiceOuterClass.internal_static_ComputeRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ComputeServiceOuterClass.ComputeRequest.class, ComputeServiceOuterClass.ComputeRequest.Builder.class);
    }

    private int bitField0_;
    public static final int INPUTFILE_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object inputFile_ = "";
    /**
     * <code>optional string inputFile = 1;</code>
     * @return Whether the inputFile field is set.
     */
    @java.lang.Override
    public boolean hasInputFile() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string inputFile = 1;</code>
     * @return The inputFile.
     */
    @java.lang.Override
    public java.lang.String getInputFile() {
      java.lang.Object ref = inputFile_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          inputFile_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string inputFile = 1;</code>
     * @return The bytes for inputFile.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getInputFileBytes() {
      java.lang.Object ref = inputFile_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        inputFile_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int OUTPUTFILE_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object outputFile_ = "";
    /**
     * <code>optional string outputFile = 2;</code>
     * @return Whether the outputFile field is set.
     */
    @java.lang.Override
    public boolean hasOutputFile() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string outputFile = 2;</code>
     * @return The outputFile.
     */
    @java.lang.Override
    public java.lang.String getOutputFile() {
      java.lang.Object ref = outputFile_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          outputFile_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string outputFile = 2;</code>
     * @return The bytes for outputFile.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getOutputFileBytes() {
      java.lang.Object ref = outputFile_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        outputFile_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DELIM_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object delim_ = "";
    /**
     * <code>optional string delim = 3;</code>
     * @return Whether the delim field is set.
     */
    @java.lang.Override
    public boolean hasDelim() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string delim = 3;</code>
     * @return The delim.
     */
    @java.lang.Override
    public java.lang.String getDelim() {
      java.lang.Object ref = delim_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          delim_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string delim = 3;</code>
     * @return The bytes for delim.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDelimBytes() {
      java.lang.Object ref = delim_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        delim_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, inputFile_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, outputFile_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, delim_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, inputFile_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, outputFile_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, delim_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ComputeServiceOuterClass.ComputeRequest)) {
        return super.equals(obj);
      }
      ComputeServiceOuterClass.ComputeRequest other = (ComputeServiceOuterClass.ComputeRequest) obj;

      if (hasInputFile() != other.hasInputFile()) return false;
      if (hasInputFile()) {
        if (!getInputFile()
            .equals(other.getInputFile())) return false;
      }
      if (hasOutputFile() != other.hasOutputFile()) return false;
      if (hasOutputFile()) {
        if (!getOutputFile()
            .equals(other.getOutputFile())) return false;
      }
      if (hasDelim() != other.hasDelim()) return false;
      if (hasDelim()) {
        if (!getDelim()
            .equals(other.getDelim())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasInputFile()) {
        hash = (37 * hash) + INPUTFILE_FIELD_NUMBER;
        hash = (53 * hash) + getInputFile().hashCode();
      }
      if (hasOutputFile()) {
        hash = (37 * hash) + OUTPUTFILE_FIELD_NUMBER;
        hash = (53 * hash) + getOutputFile().hashCode();
      }
      if (hasDelim()) {
        hash = (37 * hash) + DELIM_FIELD_NUMBER;
        hash = (53 * hash) + getDelim().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ComputeServiceOuterClass.ComputeRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ComputeServiceOuterClass.ComputeRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ComputeServiceOuterClass.ComputeRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ComputeServiceOuterClass.ComputeRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ComputeServiceOuterClass.ComputeRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ComputeServiceOuterClass.ComputeRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ComputeServiceOuterClass.ComputeRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ComputeServiceOuterClass.ComputeRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static ComputeServiceOuterClass.ComputeRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static ComputeServiceOuterClass.ComputeRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ComputeServiceOuterClass.ComputeRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ComputeServiceOuterClass.ComputeRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ComputeServiceOuterClass.ComputeRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ComputeRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ComputeRequest)
        ComputeServiceOuterClass.ComputeRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ComputeServiceOuterClass.internal_static_ComputeRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ComputeServiceOuterClass.internal_static_ComputeRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ComputeServiceOuterClass.ComputeRequest.class, ComputeServiceOuterClass.ComputeRequest.Builder.class);
      }

      // Construct using ComputeServiceOuterClass.ComputeRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        inputFile_ = "";
        outputFile_ = "";
        delim_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ComputeServiceOuterClass.internal_static_ComputeRequest_descriptor;
      }

      @java.lang.Override
      public ComputeServiceOuterClass.ComputeRequest getDefaultInstanceForType() {
        return ComputeServiceOuterClass.ComputeRequest.getDefaultInstance();
      }

      @java.lang.Override
      public ComputeServiceOuterClass.ComputeRequest build() {
        ComputeServiceOuterClass.ComputeRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ComputeServiceOuterClass.ComputeRequest buildPartial() {
        ComputeServiceOuterClass.ComputeRequest result = new ComputeServiceOuterClass.ComputeRequest(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(ComputeServiceOuterClass.ComputeRequest result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.inputFile_ = inputFile_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.outputFile_ = outputFile_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.delim_ = delim_;
          to_bitField0_ |= 0x00000004;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ComputeServiceOuterClass.ComputeRequest) {
          return mergeFrom((ComputeServiceOuterClass.ComputeRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ComputeServiceOuterClass.ComputeRequest other) {
        if (other == ComputeServiceOuterClass.ComputeRequest.getDefaultInstance()) return this;
        if (other.hasInputFile()) {
          inputFile_ = other.inputFile_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.hasOutputFile()) {
          outputFile_ = other.outputFile_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (other.hasDelim()) {
          delim_ = other.delim_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                inputFile_ = input.readBytes();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                outputFile_ = input.readBytes();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                delim_ = input.readBytes();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object inputFile_ = "";
      /**
       * <code>optional string inputFile = 1;</code>
       * @return Whether the inputFile field is set.
       */
      public boolean hasInputFile() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional string inputFile = 1;</code>
       * @return The inputFile.
       */
      public java.lang.String getInputFile() {
        java.lang.Object ref = inputFile_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            inputFile_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string inputFile = 1;</code>
       * @return The bytes for inputFile.
       */
      public com.google.protobuf.ByteString
          getInputFileBytes() {
        java.lang.Object ref = inputFile_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          inputFile_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string inputFile = 1;</code>
       * @param value The inputFile to set.
       * @return This builder for chaining.
       */
      public Builder setInputFile(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        inputFile_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>optional string inputFile = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearInputFile() {
        inputFile_ = getDefaultInstance().getInputFile();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>optional string inputFile = 1;</code>
       * @param value The bytes for inputFile to set.
       * @return This builder for chaining.
       */
      public Builder setInputFileBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        inputFile_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object outputFile_ = "";
      /**
       * <code>optional string outputFile = 2;</code>
       * @return Whether the outputFile field is set.
       */
      public boolean hasOutputFile() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional string outputFile = 2;</code>
       * @return The outputFile.
       */
      public java.lang.String getOutputFile() {
        java.lang.Object ref = outputFile_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            outputFile_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string outputFile = 2;</code>
       * @return The bytes for outputFile.
       */
      public com.google.protobuf.ByteString
          getOutputFileBytes() {
        java.lang.Object ref = outputFile_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          outputFile_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string outputFile = 2;</code>
       * @param value The outputFile to set.
       * @return This builder for chaining.
       */
      public Builder setOutputFile(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        outputFile_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>optional string outputFile = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearOutputFile() {
        outputFile_ = getDefaultInstance().getOutputFile();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>optional string outputFile = 2;</code>
       * @param value The bytes for outputFile to set.
       * @return This builder for chaining.
       */
      public Builder setOutputFileBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        outputFile_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object delim_ = "";
      /**
       * <code>optional string delim = 3;</code>
       * @return Whether the delim field is set.
       */
      public boolean hasDelim() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional string delim = 3;</code>
       * @return The delim.
       */
      public java.lang.String getDelim() {
        java.lang.Object ref = delim_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            delim_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string delim = 3;</code>
       * @return The bytes for delim.
       */
      public com.google.protobuf.ByteString
          getDelimBytes() {
        java.lang.Object ref = delim_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          delim_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string delim = 3;</code>
       * @param value The delim to set.
       * @return This builder for chaining.
       */
      public Builder setDelim(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        delim_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>optional string delim = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearDelim() {
        delim_ = getDefaultInstance().getDelim();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>optional string delim = 3;</code>
       * @param value The bytes for delim to set.
       * @return This builder for chaining.
       */
      public Builder setDelimBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        delim_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ComputeRequest)
    }

    // @@protoc_insertion_point(class_scope:ComputeRequest)
    private static final ComputeServiceOuterClass.ComputeRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ComputeServiceOuterClass.ComputeRequest();
    }

    public static ComputeServiceOuterClass.ComputeRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<ComputeRequest>
        PARSER = new com.google.protobuf.AbstractParser<ComputeRequest>() {
      @java.lang.Override
      public ComputeRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ComputeRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ComputeRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ComputeServiceOuterClass.ComputeRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ComputeResultOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ComputeResult)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional bool success = 1;</code>
     * @return Whether the success field is set.
     */
    boolean hasSuccess();
    /**
     * <code>optional bool success = 1;</code>
     * @return The success.
     */
    boolean getSuccess();
  }
  /**
   * Protobuf type {@code ComputeResult}
   */
  public static final class ComputeResult extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ComputeResult)
      ComputeResultOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ComputeResult.newBuilder() to construct.
    private ComputeResult(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ComputeResult() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ComputeResult();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ComputeServiceOuterClass.internal_static_ComputeResult_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ComputeServiceOuterClass.internal_static_ComputeResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ComputeServiceOuterClass.ComputeResult.class, ComputeServiceOuterClass.ComputeResult.Builder.class);
    }

    private int bitField0_;
    public static final int SUCCESS_FIELD_NUMBER = 1;
    private boolean success_ = false;
    /**
     * <code>optional bool success = 1;</code>
     * @return Whether the success field is set.
     */
    @java.lang.Override
    public boolean hasSuccess() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional bool success = 1;</code>
     * @return The success.
     */
    @java.lang.Override
    public boolean getSuccess() {
      return success_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeBool(1, success_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, success_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ComputeServiceOuterClass.ComputeResult)) {
        return super.equals(obj);
      }
      ComputeServiceOuterClass.ComputeResult other = (ComputeServiceOuterClass.ComputeResult) obj;

      if (hasSuccess() != other.hasSuccess()) return false;
      if (hasSuccess()) {
        if (getSuccess()
            != other.getSuccess()) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasSuccess()) {
        hash = (37 * hash) + SUCCESS_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getSuccess());
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ComputeServiceOuterClass.ComputeResult parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ComputeServiceOuterClass.ComputeResult parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ComputeServiceOuterClass.ComputeResult parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ComputeServiceOuterClass.ComputeResult parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ComputeServiceOuterClass.ComputeResult parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ComputeServiceOuterClass.ComputeResult parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ComputeServiceOuterClass.ComputeResult parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ComputeServiceOuterClass.ComputeResult parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static ComputeServiceOuterClass.ComputeResult parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static ComputeServiceOuterClass.ComputeResult parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ComputeServiceOuterClass.ComputeResult parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ComputeServiceOuterClass.ComputeResult parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ComputeServiceOuterClass.ComputeResult prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ComputeResult}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ComputeResult)
        ComputeServiceOuterClass.ComputeResultOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ComputeServiceOuterClass.internal_static_ComputeResult_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ComputeServiceOuterClass.internal_static_ComputeResult_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ComputeServiceOuterClass.ComputeResult.class, ComputeServiceOuterClass.ComputeResult.Builder.class);
      }

      // Construct using ComputeServiceOuterClass.ComputeResult.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        success_ = false;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ComputeServiceOuterClass.internal_static_ComputeResult_descriptor;
      }

      @java.lang.Override
      public ComputeServiceOuterClass.ComputeResult getDefaultInstanceForType() {
        return ComputeServiceOuterClass.ComputeResult.getDefaultInstance();
      }

      @java.lang.Override
      public ComputeServiceOuterClass.ComputeResult build() {
        ComputeServiceOuterClass.ComputeResult result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ComputeServiceOuterClass.ComputeResult buildPartial() {
        ComputeServiceOuterClass.ComputeResult result = new ComputeServiceOuterClass.ComputeResult(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(ComputeServiceOuterClass.ComputeResult result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.success_ = success_;
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ComputeServiceOuterClass.ComputeResult) {
          return mergeFrom((ComputeServiceOuterClass.ComputeResult)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ComputeServiceOuterClass.ComputeResult other) {
        if (other == ComputeServiceOuterClass.ComputeResult.getDefaultInstance()) return this;
        if (other.hasSuccess()) {
          setSuccess(other.getSuccess());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                success_ = input.readBool();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private boolean success_ ;
      /**
       * <code>optional bool success = 1;</code>
       * @return Whether the success field is set.
       */
      @java.lang.Override
      public boolean hasSuccess() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional bool success = 1;</code>
       * @return The success.
       */
      @java.lang.Override
      public boolean getSuccess() {
        return success_;
      }
      /**
       * <code>optional bool success = 1;</code>
       * @param value The success to set.
       * @return This builder for chaining.
       */
      public Builder setSuccess(boolean value) {

        success_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool success = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSuccess() {
        bitField0_ = (bitField0_ & ~0x00000001);
        success_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ComputeResult)
    }

    // @@protoc_insertion_point(class_scope:ComputeResult)
    private static final ComputeServiceOuterClass.ComputeResult DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ComputeServiceOuterClass.ComputeResult();
    }

    public static ComputeServiceOuterClass.ComputeResult getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<ComputeResult>
        PARSER = new com.google.protobuf.AbstractParser<ComputeResult>() {
      @java.lang.Override
      public ComputeResult parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ComputeResult> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ComputeResult> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ComputeServiceOuterClass.ComputeResult getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ComputeRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ComputeRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ComputeResult_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ComputeResult_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024ComputeService.proto\"F\n\016ComputeRequest" +
      "\022\021\n\tinputFile\030\001 \001(\t\022\022\n\noutputFile\030\002 \001(\t\022" +
      "\r\n\005delim\030\003 \001(\t\" \n\rComputeResult\022\017\n\007succe" +
      "ss\030\001 \001(\0102>\n\016ComputeService\022,\n\007Compute\022\017." +
      "ComputeRequest\032\016.ComputeResult\"\000"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ComputeRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ComputeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ComputeRequest_descriptor,
        new java.lang.String[] { "InputFile", "OutputFile", "Delim", });
    internal_static_ComputeResult_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ComputeResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ComputeResult_descriptor,
        new java.lang.String[] { "Success", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
